name: "Auto Tagger Action"
description: "Action to generate tags automatically using semver versioning."
author: "notdodo"
inputs:
  default_bump_strategy:
    description: "Bump strategy to use by default if no instruction is provided."
    default: "skip"
  prefix:
    description: "Prefix to use for tag generation (e.g., 'v')."
    default: ""
  suffix:
    description: "Suffix to use for tag generation (e.g., '-test')."
    default: ""
  main_branch:
    description: "Main branch to bind the tag to (e.g., 'master')."
    default: "main"
  github_token:
    description: "The GITHUB_TOKEN required to create the tag from the action."
    default: ""
    required: true
  dry_run:
    description: "Run the Action in dry-run mode: do not create tags."
    default: "false"
runs:
  using: "docker"
  image: "Dockerfile"
