on:
  workflow_call:
    inputs:
      runs-on:
        type: string
        default: "ubuntu-latest"
    secrets:
      token:
        description: "asdfa"
        required: true

jobs:
  gitleaks:
    name: gitleaks
    runs-on: ${{ inputs.runs-on }}
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        # v4.1.2
        with:
          fetch-depth: 0
      - name: gitleaks
        uses: gitleaks/gitleaks-action@e6dab246340401bf53eec993b8f05aebe80ac636
        # V2.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.token }}
          GITLEAKS_VERSION: latest
