name: Golang CI
on:
  push:
    branches:
      - main
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"
  pull_request:
    paths:
      - "**.go"
      - "go.mod"
      - "go.sum"

concurrency:
  group: iamme-ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    uses: notdodo/test-GHAs/.github/workflows/goci.yml@main
