on:
  workflow_call:
    inputs:
      go-version:
        type: string
        default: "1.20"
      runs-on:
        type: string
        default: "ubuntu-latest"
      working-directory:
        type: string
        default: "."

jobs:
  go-lint:
    name: Golang Linting
    runs-on: ${{ inputs.runs-on }}
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    permissions:
      contents: read
      pull-requests: read
      checks: write
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633
        # v4.1.2
        with:
          fetch-depth: 0
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491
        # v5.0.0
        with:
          go-version: ${{ inputs.go-version }}
      - name: golangci-lint
        uses: golangci/golangci-lint-action@3cfe3a4abbb849e10058ce4af15d205b6da42804
        # v4.0.0
        with:
          version: latest
          only-new-issues: true
          # skip-cache: true
