name: Matrix example test

on:
  workflow_dispatch:

jobs:
  print-stuff:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - environment: staging
            id: 111111
          - environment: production
            id: 999999
    steps:
      - name: ${{ matrix.environment }}
        env:
          ACCOUNT: account/${{ matrix.id }}
        run: |
          echo ${{ matrix.environment }}
          echo ${ACCOUNT}
