name: Stuff with bash

on:
  workflow_dispatch:
  pull_request:

jobs:
  do-stuff:
    name: Stuff
    permissions:
      id-token: write
      contents: read
    steps:
      - name: do bash stuff
        shell: bash
        run: | 
          branch=$(echo "${{ github.event.ref }}" | tr "/" - |  sed -e 's/^refs-heads-//')
          if [ -n "${branch}" ]; then
            ls "$branch"
          else
            echo "Did not receive branch variable correctly"
          fi
