on:
  workflow_call:
    inputs:
      working-directory:
        required: false
        type: string
        default: .
        description: "Directory where to execute workflow actions. Defaults to '.'"
      rust-toolchain-version:
        required: false
        default: "almeno 3"
        type: string

jobs:
  cargo_build:
    name: Cargo Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}
    steps:
      - uses: actions/checkout@v3
      - name: ls
        run: |
          ls -la
      - uses: notdodo/test-GHAs/actions/install-rust@main
        with:
          rust-toolchain: ${{ inputs.rust-toolchain-version }}
          working-directory: ${{ inputs.working-directory }}
