name: test-auto-tag
on: [push, pull_request]
jobs:
  auto-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run action
        uses: notdodo/test-GHAs/auto-tag@main
        with:
          bind_to_major: true
          default_bump_strategy: skip
          default_branch: main
          prefix: test-v
          github_token: ${{ secrets.GITHUB_TOKEN }}
          dry_run: false
