name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run action
        uses: notdodo/test-GHAs/auto-tag@main
        with:
          bump_strategy: minor
          prefix: "v"
          suffix: "-test"
          main_branch: "main"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          printenv
