name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@master
      - name: Run action

        # Put your action repo here
        uses: notdodo/test-GHAs/auto-tag@main

        # Put an example of your mandatory inputs here
        with:
          myInput: world
      - run: |
          echo "Hello $1"
          time=$(date)
          echo "time=$time" >> $GITHUB_OUTPUT
