name: My Workflow
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run action

        # Put your action repo here
        uses: notdodo/test-GHAs/auto-tag@main

        # Put an example of your mandatory inputs here
        with:
          bump_strategy: minor
          prefix: "v"
          suffix: "-test"
          main_branch: "main"
