name: Var

on:
  workflow_dispatch:

jobs:
  print-secrets:
    runs-on: ubuntu-latest
    environment: cs
    steps:
      - name: Install yq
        uses: primait/setup-yq@3d931309f27270ebbafd53f2daee773a82ea1822
        # v1.0.1
        with:
          yq-version: "v4.44.5"
    
      - uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4
        # v2.7.1
        with:
          egress-policy: audit
      - uses: actions/checkout@v3
      - name: load secrets
        run: |
          S="PASSWORD";
          ASDF=${{ secrets[0] }};
          if [[ $ASDF == *"PASSWORD"* ]]; then
            echo "This is the password!"
          else
            echo "rip"
          fi

          ASDF=${{ secrets }};
          echo ${ASDF[@]};
          if [[ ${ASDF[0]} == *"PASSWORD"* ]]; then
            echo "This is the password!";
          else
            echo "rip";
          fi

          TESTP=${{ secrets.PASSWORD }}
          if [[ $TESTP == *"PASSWORD"* ]]; then
            echo "This is the password!"
          else
            echo "rip"
          fi
      - run: env
